-- Seed: 63 tournament slots
-- R64 teams use 2015 bracket as placeholder — update after Selection Sunday (Mar 15 2026).
-- Run in Supabase SQL Editor after schema.sql.

insert into public.games (id, espn_id, slot_index, round, region, teams, winner, status, updated_at) values
  (gen_random_uuid(), null, 0,  'R64', 'midwest', jsonb_build_object('team1','Kentucky',   'seed1',1, 'team2','Hampton',     'seed2',16), null, 'pending', now()),
  (gen_random_uuid(), null, 1,  'R64', 'midwest', jsonb_build_object('team1','Cincinnati',  'seed1',8, 'team2','Purdue',       'seed2',9),  null, 'pending', now()),
  (gen_random_uuid(), null, 2,  'R64', 'midwest', jsonb_build_object('team1','W. Virginia', 'seed1',5, 'team2','Buffalo',      'seed2',12), null, 'pending', now()),
  (gen_random_uuid(), null, 3,  'R64', 'midwest', jsonb_build_object('team1','Maryland',    'seed1',4, 'team2','Valparaiso',   'seed2',13), null, 'pending', now()),
  (gen_random_uuid(), null, 4,  'R64', 'midwest', jsonb_build_object('team1','Butler',      'seed1',6, 'team2','Texas',        'seed2',11), null, 'pending', now()),
  (gen_random_uuid(), null, 5,  'R64', 'midwest', jsonb_build_object('team1','Notre Dame',  'seed1',3, 'team2','Northeastern', 'seed2',14), null, 'pending', now()),
  (gen_random_uuid(), null, 6,  'R64', 'midwest', jsonb_build_object('team1','Wichita St',  'seed1',7, 'team2','Indiana',      'seed2',10), null, 'pending', now()),
  (gen_random_uuid(), null, 7,  'R64', 'midwest', jsonb_build_object('team1','Kansas',      'seed1',2, 'team2','New Mex. St',  'seed2',15), null, 'pending', now()),
  (gen_random_uuid(), null, 8,  'R32', 'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 9,  'R32', 'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 10, 'R32', 'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 11, 'R32', 'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 12, 'S16', 'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 13, 'S16', 'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 14, 'E8',  'midwest', null, null, 'pending', now()),
  (gen_random_uuid(), null, 15, 'R64', 'west', jsonb_build_object('team1','Wisconsin',   'seed1',1, 'team2','Coastal Car.',  'seed2',16), null, 'pending', now()),
  (gen_random_uuid(), null, 16, 'R64', 'west', jsonb_build_object('team1','Oregon',      'seed1',8, 'team2','Oklahoma St',   'seed2',9),  null, 'pending', now()),
  (gen_random_uuid(), null, 17, 'R64', 'west', jsonb_build_object('team1','Arkansas',    'seed1',5, 'team2','Wofford',       'seed2',12), null, 'pending', now()),
  (gen_random_uuid(), null, 18, 'R64', 'west', jsonb_build_object('team1','N. Carolina', 'seed1',4, 'team2','Harvard',       'seed2',13), null, 'pending', now()),
  (gen_random_uuid(), null, 19, 'R64', 'west', jsonb_build_object('team1','Xavier',      'seed1',6, 'team2','Ole Miss',      'seed2',11), null, 'pending', now()),
  (gen_random_uuid(), null, 20, 'R64', 'west', jsonb_build_object('team1','Baylor',      'seed1',3, 'team2','Georgia St',    'seed2',14), null, 'pending', now()),
  (gen_random_uuid(), null, 21, 'R64', 'west', jsonb_build_object('team1','VCU',         'seed1',7, 'team2','Ohio St',       'seed2',10), null, 'pending', now()),
  (gen_random_uuid(), null, 22, 'R64', 'west', jsonb_build_object('team1','Arizona',     'seed1',2, 'team2','Tex. Southern', 'seed2',15), null, 'pending', now()),
  (gen_random_uuid(), null, 23, 'R32', 'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 24, 'R32', 'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 25, 'R32', 'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 26, 'R32', 'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 27, 'S16', 'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 28, 'S16', 'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 29, 'E8',  'west', null, null, 'pending', now()),
  (gen_random_uuid(), null, 30, 'R64', 'south', jsonb_build_object('team1','Duke',         'seed1',1, 'team2','R. Morris',    'seed2',16), null, 'pending', now()),
  (gen_random_uuid(), null, 31, 'R64', 'south', jsonb_build_object('team1','San Diego St', 'seed1',8, 'team2','St. Johns',    'seed2',9),  null, 'pending', now()),
  (gen_random_uuid(), null, 32, 'R64', 'south', jsonb_build_object('team1','Utah',         'seed1',5, 'team2','SF Austin',    'seed2',12), null, 'pending', now()),
  (gen_random_uuid(), null, 33, 'R64', 'south', jsonb_build_object('team1','Georgetown',   'seed1',4, 'team2','E. Washington','seed2',13), null, 'pending', now()),
  (gen_random_uuid(), null, 34, 'R64', 'south', jsonb_build_object('team1','SMU',          'seed1',6, 'team2','UCLA',         'seed2',11), null, 'pending', now()),
  (gen_random_uuid(), null, 35, 'R64', 'south', jsonb_build_object('team1','Iowa St',      'seed1',3, 'team2','UAB',          'seed2',14), null, 'pending', now()),
  (gen_random_uuid(), null, 36, 'R64', 'south', jsonb_build_object('team1','Iowa',         'seed1',7, 'team2','Davidson',     'seed2',10), null, 'pending', now()),
  (gen_random_uuid(), null, 37, 'R64', 'south', jsonb_build_object('team1','Gonzaga',      'seed1',2, 'team2','N. Dakota St', 'seed2',15), null, 'pending', now()),
  (gen_random_uuid(), null, 38, 'R32', 'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 39, 'R32', 'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 40, 'R32', 'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 41, 'R32', 'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 42, 'S16', 'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 43, 'S16', 'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 44, 'E8',  'south', null, null, 'pending', now()),
  (gen_random_uuid(), null, 45, 'R64', 'east', jsonb_build_object('team1','Villanova',   'seed1',1, 'team2','Lafayette',  'seed2',16), null, 'pending', now()),
  (gen_random_uuid(), null, 46, 'R64', 'east', jsonb_build_object('team1','NC State',    'seed1',8, 'team2','LSU',        'seed2',9),  null, 'pending', now()),
  (gen_random_uuid(), null, 47, 'R64', 'east', jsonb_build_object('team1','N. Iowa',     'seed1',5, 'team2','Wyoming',    'seed2',12), null, 'pending', now()),
  (gen_random_uuid(), null, 48, 'R64', 'east', jsonb_build_object('team1','Louisville',  'seed1',4, 'team2','UC Irvine',  'seed2',13), null, 'pending', now()),
  (gen_random_uuid(), null, 49, 'R64', 'east', jsonb_build_object('team1','Providence',  'seed1',6, 'team2','Dayton',     'seed2',11), null, 'pending', now()),
  (gen_random_uuid(), null, 50, 'R64', 'east', jsonb_build_object('team1','Oklahoma',    'seed1',3, 'team2','Albany',     'seed2',14), null, 'pending', now()),
  (gen_random_uuid(), null, 51, 'R64', 'east', jsonb_build_object('team1','Michigan St', 'seed1',7, 'team2','Georgia',    'seed2',10), null, 'pending', now()),
  (gen_random_uuid(), null, 52, 'R64', 'east', jsonb_build_object('team1','Virginia',    'seed1',2, 'team2','Belmont',    'seed2',15), null, 'pending', now()),
  (gen_random_uuid(), null, 53, 'R32', 'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 54, 'R32', 'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 55, 'R32', 'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 56, 'R32', 'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 57, 'S16', 'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 58, 'S16', 'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 59, 'E8',  'east', null, null, 'pending', now()),
  (gen_random_uuid(), null, 60, 'F4',    null, null, null, 'pending', now()),
  (gen_random_uuid(), null, 61, 'F4',    null, null, null, 'pending', now()),
  (gen_random_uuid(), null, 62, 'Champ', null, null, null, 'pending', now());
